AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy Urma Deal Genie Lambda function'

Parameters:
  ApiKey:
    Type: String
    Description: 3commas API key with "Bots read" and "Bots write" permissions
  ApiSecret:
    Type: String
    Description: 3commas API secret for the ApiKey
  S3Bucket:
    Type: String
    Description: Name of the S3 bucket containing the lambda package and config
  PackageFilename:
    Type: String
    Description: Filename of the lambda function package in S3

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Urmagurd-LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: "Urmagurd-ReadS3"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3Bucket}/*

  UrmaDealGenie:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: UrmaDealGenie
      Description: Urma Deal Genie lambda function
      Handler: "UrmaDealGenie::UrmaDealGenie.Function::FunctionHandler"
      Runtime: dotnetcore3.1
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Timeout: 120
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref PackageFilename
      Environment:
        Variables:
          APIKEY: !Ref ApiKey
          SECRET: !Ref ApiSecret
          BUCKET: !Ref S3Bucket

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Name: UrmaDealGenie-Schedule
      Description: "Urma Deal Genie Scheduled rule"
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets: 
        - Arn: 
            Fn::GetAtt: 
              - "UrmaDealGenie"
              - "Arn"
          Id: "TargetFunctionV1"
          Input: '{ "LoadFromS3": false }'

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "UrmaDealGenie"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"