FROM mcr.microsoft.com/dotnet/runtime:6.0

COPY ./UrmaDealGenieApp-linux-x64/ App/
COPY ./dealrules.json App/
COPY ./appsettings.json App/
WORKDIR /App

ENTRYPOINT ["./UrmaDealGenieApp-linux-x64", ""]