name: Create deployment packages

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore ./src/UrmaDealGenieApp
      - name: Build
        run: dotnet lambda package UrmaDealGenieAWS-test.zip -pl ./src/UrmaDealGenie

