name: Release console app

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ./src/UrmaDealGenieApp
      - name: Build/publish console application
        run: dotnet publish ./src/UrmaDealGenieApp -c Release --no-restore -o ./src/UrmaDealGenieApp/publish

      - name: Package artefacts
        uses: papeloto/action-zip@v1
        with:
          files: ./src/UrmaDealGenieApp/publish
          dest: UrmaDealGenieApp-test.zip          

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Urma Deal Genie Console App  ${{ github.event.release.tag_name }}"
          files: |
            UrmaDealGenieApp-test.zip
            ./src/UrmaDealGenieApp/dealrules.json
