name: Create new release for the console application 

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ./src/UrmaDealGenieApp
      - name: Build/publish console application
        run: dotnet publish ./src/UrmaDealGenieApp -c Release --no-restore -o ./src/UrmaDealGenieApp/UrmaDealGenieApp

      - name: Package artefacts
        uses: papeloto/action-zip@v1
        with:
          files: ./src/UrmaDealGenieApp/UrmaDealGenieApp
          dest: UrmaDealGenieApp-test.zip          

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            UrmaDealGenieApp-test.zip
            dealrules.json
